//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.ProductoTerminadoes = new HashSet<ProductoTerminado>();
        }
    
        public int idEmpleado { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string cedula { get; set; }
        public string contraseña { get; set; }
        public string tokenRecovery { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<System.DateTime> ultimoIntento { get; set; }
    
        public virtual Estado_Empleado Estado_Empleado { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoTerminado> ProductoTerminadoes { get; set; }
    }
}
