//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using DColor.Entities;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.ProductoTerminadoes = new HashSet<ProductoTerminado>();
        }
    
        public int idEmpleado { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        [Required(ErrorMessage = "El Correo es obligatorio no se puede dejar espacios en blanco")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Este email no es permitido")]
        public string correo { get; set; }
        public string cedula { get; set; }
        public string contraseña { get; set; }
        public string tokenRecovery { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<System.DateTime> ultimoIntento { get; set; }
    
        public virtual Estado_Empleado Estado_Empleado { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoTerminado> ProductoTerminadoes { get; set; }
        public List<PermisosObj> listaPermisos { get; set; }
    }
}
