//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EstadoCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoCliente()
        {
            this.Clientes = new HashSet<Cliente>();
        }
        [Required(ErrorMessage = "El Id EstadoCliente es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Id EstadoCliente")]
        public int idEstadoCliente { get; set; }
        [Required(ErrorMessage = "El Estado Cliente es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Estado Cliente")]
        public string estadoCliente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
