//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Estado_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado_Empleado()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
        [Required(ErrorMessage = "El Id EstadoEmpleado es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Id EstadoEmpleado")]
        public int idEstado { get; set; }
        [Required(ErrorMessage = "El Estado Empleado es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Estado Empleado")]
        public string estadoEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
