//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Insumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumo()
        {
            this.Materiales_Trabajo = new HashSet<Materiales_Trabajo>();
        }
        [Required(ErrorMessage = "El Id Producto es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Id Producto")]
        public int idProducto { get; set; }

        [Required(ErrorMessage = "El Id Proveedor es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Nombre Proveedor")]
        public Nullable<int> idProveedor { get; set; }

        [Required(ErrorMessage = "El Nombre es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "La marca es obligatoria no se puede dejar espacios en blanco")]
        [DisplayName("Marca")]
        public string marca { get; set; }

        [Required(ErrorMessage = "La Cantidad es obligatoria no se puede dejar espacios en blanco")]
        [DisplayName("Cantidad")]
        public Nullable<int> cantidad { get; set; }

        [Required(ErrorMessage = "El Precio es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Precio")]
        public Nullable<int> precio { get; set; }

        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiales_Trabajo> Materiales_Trabajo { get; set; }
    }
}
