//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales_Trabajo
    {
        public int idMaterial { get; set; }
        public Nullable<int> idTrabajo { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> precio { get; set; }
        public string nombreProducto { get; set; }
        public string nombreEmpleado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual ProductoTerminado ProductoTerminado { get; set; }
    }
}
