//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DColorEntities : DbContext
    {
        public DColorEntities()
            : base("name=DColorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Estado_Empleado> Estado_Empleadoes { get; set; }
        public virtual DbSet<Estado_Trabajo> Estado_Trabajoes { get; set; }
        public virtual DbSet<EstadoCliente> EstadoClientes { get; set; }
        public virtual DbSet<EstadoDePedido> EstadoDePedidoes { get; set; }
        public virtual DbSet<Insumo> Insumos { get; set; }
        public virtual DbSet<Materiales_Trabajo> Materiales_Trabajoes { get; set; }
        public virtual DbSet<Modulo> Moduloes { get; set; }
        public virtual DbSet<Operacione> Operaciones { get; set; }
        public virtual DbSet<Pedido> Pedidos { get; set; }
        public virtual DbSet<ProductoTerminado> ProductoTerminadoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Rol_Operacion> Rol_Operacions { get; set; }
    }
}
