//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Operacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operacione()
        {
            this.Rol_Operacion = new HashSet<Rol_Operacion>();
        }
        [Required(ErrorMessage = "El Id Operacion es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Id Operacion")]
        public int id { get; set; }

        [Required(ErrorMessage = "El Nombre Operacion es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Nombre Operacion")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El Nombre Modulo es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Nombre Modulo")]
        public Nullable<int> idModulo { get; set; }

        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol_Operacion> Rol_Operacion { get; set; }
    }
}