//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int idPedido { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fechaEntregaEstimada { get; set; }
        public Nullable<int> idEstadoPedido { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string horaEntregaPedido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoDePedido EstadoDePedido { get; set; }
    }
}
