//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int idPedido { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fechaEntregaEstimada { get; set; }
        public Nullable<int> idEstadoPedido { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string horaEntregaPedido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoDePedido EstadoDePedido { get; set; }
    }
}
