//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DColor.Entities;

    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Insumos = new HashSet<Insumo>();
        }
    
        public int idProveedor { get; set; }
        [Required(ErrorMessage = "El Nombre es obligatorio no se puede dejar espacios en blanco")]
        [DisplayName("Nombre Proveedor")]
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public string correo { get; set; }
        public string apellidos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumo> Insumos { get; set; }
    }
}
