//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DColor.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Rol_Operacion
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [DisplayName("Id único de permiso")]
        public int id { get; set; }
        [DisplayName("Id del rol relacionado al permiso")]
        public Nullable<int> idRol { get; set; }
        [DisplayName("Id de la operación relacionada al permiso")]
        public Nullable<int> idOperacion { get; set; }

        public virtual Operacione Operacione { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
